export const SPONSOR_DETAILS_REQUESTED = "SPONSOR_DETAILS_REQUESTED";
export const SPONSOR_DETAILS_SUCCESS = "SPONSOR_DETAILS_SUCCESS";
export const SPONSOR_DETAILS_FAILED = "SPONSOR_DETAILS_FAILED";
export const SPONSOR_DETAILS_SAVE = "SPONSOR_DETAILS_SAVE";
export const SPONSOR_STATE_POPULATE = "SPONSOR_STATE_POPULATE";
export const FIELD_CHANGE = "FIELD_CHANGE";
export const SPONSOR_FIELD_OPTIONS_REQUESTED =
  "SPONSOR_FIELD_OPTIONS_REQUESTED";
export const SPONSOR_FIELD_OPTIONS_FAILED = "SPONSOR_FIELD_OPTIONS_FAILED";
export const SPONSOR_FIELD_OPTIONS_SUCCESS = "SPONSOR_FIELD_OPTIONS_SUCCESS";

export const SPONSOR_NEW_SUBMITTED = "SPONSOR_NEW_SUBMITTED";
export const SPONSOR_NEW_SUCCESS = "SPONSOR_NEW_SUCCESS";
export const SPONSOR_NEW_FAILED = "SPONSOR_NEW_FAILED";
export const SPONSOR_NEW_SAVE_FIELD_STATE = "SPONSOR_NEW_SAVE_FIELD_STATE";
export const SPONSOR_NEW_NEXT_STEP = "SPONSOR_NEW_NEXT_STEP";
export const SPONSOR_NEW_PREV_STEP = "SPONSOR_NEW_PREV_STEP";
export const SPONSOR_NEW_TOGGLE_NEW_ASSET = "SPONSOR_NEW_TOGGLE_NEW_ASSET";

export const SPONSOR_NEW_SAVE_ASSET_FIELD = "SPONSOR_NEW_SAVE_ASSET_FIELD";
export const SPONSOR_EXISTING_SAVE_ASSET_FIELD =
  "SPONSOR_EXISTING_SAVE_ASSET_FIELD";
export const SPONSOR_SAVE_ALL_ASSETS = "SPONSOR_SAVE_ALL_ASSETS";
export const SPONSOR_EDIT_ASSET = "SPONSOR_EDIT_ASSET";

export const SPONSOR_ERROR = "SPONSOR_ERROR";
export const SPONSOR_NEW_INIT = "SPONSOR_NEW_INIT";
export const SPONSOR_RESET_STEP = "SPONSOR_RESET_STEP";
export const SPONSOR_MOVE_TO_STEP = "SPONSOR_MOVE_TO_STEP";

export const SPONSOR_ERRORS_CLEAR = "SPONSOR_ERRORS_CLEAR";

export const SPONSOR_DETAILS_SAVED_SUCCESS = "SPONSOR_DETAILS_SAVED_SUCCESS";

export const SPONSOR_CLEAR_ALERTS = "SPONSOR_CLEAR_ALERTS";

export const SPONSOR_SET_ID = "SPONSOR_SET_ID";

/**
 * Action generators
 */

export function clearErrorsAction() {
  return {
    type: SPONSOR_ERRORS_CLEAR,
  };
}

export function setSPONSORIDAction(id) {
  return {
    type: SPONSOR_SET_ID,
    id: id,
  };
}
